server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #向注册中心注册自己
    register-with-eureka: true
    #是否从Eureka Server抓取已有注册信息，集群必须设置为true
    fetch-registry: true
    service-url:
      #地址查询服务和注册服务都需要依赖这个地址
      # defaultZone: http://eureka-server-7001:7001/eureka/
      defaultZone: http://eureka-server-7001:7001/eureka/,http://eureka-server-7002:7002/eureka/ #集群模式
