server:
  port: 80
spring:
  application:
    name: consumer-order-feign-hystrix
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-7001:7001/eureka/
feign:
  hystrix:
    enabled: true