server:
  port: 8571
spring:
  application:
    name: cloud-sleuth-service-8571
  zipkin:
    # 放到 zipkin上
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率介于0-1之间，1表示全部采集
      probability: 1
eureka:
  client:
    service-url:
      #defaultZone: http://eureka-server-7001:7001/eureka/,http://eureka-server-7002:7002/eureka/ #集群版
      defaultZone: http://eureka-server-7001:7001/eureka/  #单机版