server:
  port: 9527
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态获取路由的功能，利用微服务名进行路由
      routes:
        - id: payment-route
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**
        - id: baidu-news
          uri: https://news.baidu.com
          predicates:
            - Path=/guonei
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-7001:7001/eureka/