server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.zsh.springcloud.entities

eureka:
  client:
    #向注册中心注册自己
    register-with-eureka: true
    #是否从Eureka Server抓取已有注册信息，集群必须设置为true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka-server-7001:7001/eureka/,http://eureka-server-7002:7002/eureka/ #集群版
      #地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka-server-7001:7001/eureka/  #单机版
  instance:
    instance-id: payment8001 #服务名和端口的别称，可根据公司要求自定义
    prefer-ip-address: true #访问路径显示IP
    lease-renewal-interval-in-seconds: 30 #客户端向服务端发送心跳的间隔
    lease-expiration-duration-in-seconds: 90 #服务端在收到该客户端最后一次心跳后的等待时长上限，超时删除服务